### PR TITLE
Fixing typescript version

### PR DESCRIPTION
**Pull request by grigoreme**

### CODE REVIEW

**Comment by grigoreme** [comment]
Getting unknown and understandable codeclimate error.
**Hotfix for now:** Enter in packages.json and rename `"typescript": "^2.0.10",` into `"typescript": "2.0.10",`
Help wanted.

**Comment by grigoreme** [comment]
Codeclimate gives a fake error, as for example, I made another pull request with same changes which passed.  ( https://github.com/MitocGroup/deep-microservices-root-angular/pull/105 ).
Local Codeclimate CLI gives next output: 
P.S. `src/deep-root-angular/frontend/webpack.config.js ` is shows as warning not error, and is presend in much of pull requests.
```grigoreme@py-user:~/ATM/deep-microservices-root-angular$ sudo codeclimate analyze src/deep-root-angular/frontend/
Starting analysis
Running csslint: Done!
Running duplication: Done!
Running eslint: Done!
Running fixme: Done!

== src/deep-root-angular/frontend/webpack.config.js (14 issues) ==
11: Unexpected trailing comma. [eslint]
16: Unexpected trailing comma. [eslint]
20: Unexpected trailing comma. [eslint]
32: Unexpected trailing comma. [eslint]
38: Unexpected trailing comma. [eslint]
50: Unexpected trailing comma. [eslint]
54: Unexpected trailing comma. [eslint]
59: Unexpected trailing comma. [eslint]
63: Unexpected trailing comma. [eslint]
64: Unexpected trailing comma. [eslint]
65: Unexpected trailing comma. [eslint]
70: Unexpected trailing comma. [eslint]
71: Unexpected trailing comma. [eslint]
78: Unexpected trailing comma. [eslint]

Analysis complete! Found 14 issues.
```

**Comment by ddimitrioglo** [comment]
merge with eugene's approve

**Review by ddimitrioglo — APPROVED** [review]
merge with eugene's approve

**Pull request merged**
